- name: Upload S3
  # You may pin to the exact commit or the version.
  # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
  uses: shallwefootball/upload-s3-action@v1.1.3
  with:
    # aws key id
    aws_key_id: 
    # aws secret access key
    aws_secret_access_key: 
    # aws bucket name
    aws_bucket: 
    # directory to upload
    source_dir: 
    # destination directory for upload
    destination_dir: # optional, default is /
